version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000" # Map the host port to the container port
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80" # Map the host port to the container port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
